### ISSUE TITLE
Build and run iOS application

### ISSUE THREAD

**Issue by DonJayamanne** [pybee/briefcase#128]
I'm unable to build and run an iOS application on a Mac:

**Error message received:**
`
"/Users/donjayamanne/Desktop/Development/PythonStuff/beewareSample/folders/appname/venv/lib/python3.6/site-packages/briefcase/ios.py", line 150, in build_app
    build_settings_str = ['{}={}'.format(x for x in build_settings)]
IndexError: tuple index out of range
`

**Information:**
* MacOS HighSierra Version 10.13.4 (17E199) 
* Python 3.6.5 (virtualenv)
* XCode Version 9.3 (9E145)
* I'm able to develop, build and run iOS apps (in Objective C)

**Steps to reproduce:**
* Use cookiecutter to create project (use defaults)
* Create virtual env `virtualenv --python=3.6 venv`
* Install beeware (`pip install beeware`)
* Build iOS project, here's the output (success)
<section><details>

```shell
$ beeware build ios
Running Briefcase...
>>> python setup.py ios

running ios

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-ios==0.3.0.dev8
  Using cached https://files.pythonhosted.org/packages/67/6e/d0aff2728c47e530516ac7d1f331d1679b8664b00ec74248090d11a30d84/toga_iOS-0.3.0.dev8-py3-none-any.whl
Collecting rubicon-objc>=0.2.10 (from toga-ios==0.3.0.dev8)
  Using cached https://files.pythonhosted.org/packages/35/b0/aa6d839057126991d16a591c74e24c075797db7436d6c0d6e655a3e15b3a/rubicon_objc-0.2.10-py2.py3-none-any.whl
Collecting toga-core==0.3.0.dev8 (from toga-ios==0.3.0.dev8)
  Using cached https://files.pythonhosted.org/packages/a4/2e/4757cadb2206e2f6bb6136fda395dbec2d84bda86b77b5713f435b0fdb60/toga_core-0.3.0.dev8-py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev8->toga-ios==0.3.0.dev8)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: rubicon-objc, travertino, toga-core, toga-ios
Successfully installed rubicon-objc-0.2.10 toga-core-0.3.0.dev8 toga-ios-0.3.0.dev8 travertino-0.1.2
 * Installing project code...
Processing /Users/donjayamanne/Desktop/Development/PythonStuff/beewareSample/folders/appname
Building wheels for collected packages: appname
  Running setup.py bdist_wheel for appname ... done
  Stored in directory: /private/var/folders/22/0kj01mp12l3dsd1vw9vhfs6c0000gn/T/pip-ephem-wheel-cache-g4e3hwuo/wheels/83/35/3f/9792c1aeedb6706d827a27b802299fd76b879bf8b35fca4e98
Successfully built appname
Installing collected packages: appname
Successfully installed appname-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
```

</details></section>   
   
   
* Now run using `beeware run ios`, here's the output (`this fails`)

<section><details>

```shell
$ beeware run ios
Running Briefcase...
>>> python setup.py ios -s

running ios

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-ios==0.3.0.dev8
  Using cached https://files.pythonhosted.org/packages/67/6e/d0aff2728c47e530516ac7d1f331d1679b8664b00ec74248090d11a30d84/toga_iOS-0.3.0.dev8-py3-none-any.whl
Collecting rubicon-objc>=0.2.10 (from toga-ios==0.3.0.dev8)
  Using cached https://files.pythonhosted.org/packages/35/b0/aa6d839057126991d16a591c74e24c075797db7436d6c0d6e655a3e15b3a/rubicon_objc-0.2.10-py2.py3-none-any.whl
Collecting toga-core==0.3.0.dev8 (from toga-ios==0.3.0.dev8)
  Using cached https://files.pythonhosted.org/packages/a4/2e/4757cadb2206e2f6bb6136fda395dbec2d84bda86b77b5713f435b0fdb60/toga_core-0.3.0.dev8-py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev8->toga-ios==0.3.0.dev8)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: rubicon-objc, travertino, toga-core, toga-ios
Successfully installed rubicon-objc-0.2.10 toga-core-0.3.0.dev8 toga-ios-0.3.0.dev8 travertino-0.1.2
 * Installing project code...
Processing /Users/donjayamanne/Desktop/Development/PythonStuff/beewareSample/folders/appname
Building wheels for collected packages: appname
  Running setup.py bdist_wheel for appname ... done
  Stored in directory: /private/var/folders/22/0kj01mp12l3dsd1vw9vhfs6c0000gn/T/pip-ephem-wheel-cache-50wz_1en/wheels/83/35/3f/9792c1aeedb6706d827a27b802299fd76b879bf8b35fca4e98
^[[1;10DSuccessfully built appname
Installing collected packages: appname
Successfully installed appname-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'toga-django==0.3.0.dev8',
  File "/Users/donjayamanne/Desktop/Development/PythonStuff/beewareSample/folders/appname/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/donjayamanne/Desktop/Development/PythonStuff/beewareSample/folders/appname/venv/lib/python3.6/site-packages/briefcase/app.py", line 466, in run
    success = self.build_app()
  File "/Users/donjayamanne/Desktop/Development/PythonStuff/beewareSample/folders/appname/venv/lib/python3.6/site-packages/briefcase/ios.py", line 150, in build_app
    build_settings_str = ['{}={}'.format(x for x in build_settings)]
IndexError: tuple index out of range
```

</details></section>

**Comment by freakboy3742** [comment]
Ah - yes - someone reported this during the sprints, but evidently didn't submit a patch. 

It's a *really* dumb merge error that somehow slipped through testing, introduced with a patch that went from `%s` formatting to `.format()`. 

I'll patch this and get a release out RSN - it's a pretty glaring error...

**Comment by DonJayamanne** [comment]
Awesome, 
fyi, I've ironed out a few edhes of the vscode beeware extension and managed to get debugging working for macos and Linux apps. 
Will work on Windows next. Then a wiki page. 

Will let you know when you can publish the next version, hopefully on Monday.
