### ISSUE TITLE
Tutorial 0 not working

### ISSUE THREAD

**Issue by mankoff** [pybee/briefcase#56]
I've tried to follow [Tutorial 0](https://briefcase.readthedocs.io/en/latest/tutorials/tutorial-0.html) with the following commands:

Getting Started (but with a `conda` environment):

    conda create -n toga python=3.4
    source activate toga
    pip install briefcase 
  
Tutorial:

    pip install cookiecutter briefcase
    cookiecutter https://github.com/pybee/briefcase-template
    cd tutorial_0

Note, here I do not ""Add this"" to `tutorial_0/app.py` but rather **replace**. I think if it is just added, there would be two `main()` functions, which might be a problem.

Then, when try to run it with `python setup.py ios`, I get the following error:

```
$ python setup.py ios
running ios
 * Writing application template...
Template Python-iOS-template succesfully updated.
Project template: /Users/mankoff/.cookiecutters/Python-iOS-template
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    'toga-django',
  File "/Users/mankoff/local/anaconda/envs/toga/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/mankoff/local/anaconda/envs/toga/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/mankoff/local/anaconda/envs/toga/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/mankoff/local/anaconda/envs/toga/lib/python3.4/site-packages/briefcase/app.py", line 316, in run
    self.generate_app_template()
  File "/Users/mankoff/local/anaconda/envs/toga/lib/python3.4/site-packages/briefcase/app.py", line 192, in generate_app_template
    'secret_key': self.secret_key,
  File "/Users/mankoff/local/anaconda/envs/toga/lib/python3.4/site-packages/cookiecutter/main.py", line 63, in cookiecutter
    no_input=no_input,
  File "/Users/mankoff/local/anaconda/envs/toga/lib/python3.4/site-packages/cookiecutter/repository.py", line 101, in determine_repo_dir
    '\n'.join(repository_candidates)
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "/Users/mankoff/.cookiecutters/Python-iOS-template" could not be found in the following locations:
/Users/mankoff/.cookiecutters/Python-iOS-template
/Users/mankoff/.cookiecutters/Python-iOS-template
$
```

At the time of writing this issue, nothing is on Google (or Bing!) when I search for those error messages, so I thought people here might be able to help debug this.

**Comment by mankoff** [comment]
This issue is solved by manually downloading the Python support packages as explained in the non-master branches of the README (ex: https://github.com/pybee/Python-iOS-template/tree/3.4), and then building the package with the `support-pkg` option: 

    python setup.py ios --support-pkg=/path/to/Python-3.4-iOS-support.b2.tar.gz
