### ISSUE TITLE
Tutorial bug with Project-Linux-template

### ISSUE THREAD

**Issue by treyhunner** [pybee/briefcase#62]
I used the [cookiecutter template](https://github.com/pybee/briefcase-template/issues) and then did a `pip install briefcase` and tried:

```bash
$ python setup.py linux -s
```

But received this error:

```bash
$ python setup.py linux -s
running linux
 * Writing application template...
Template Python-Linux-template succesfully updated.
Project template: /home/trey/.cookiecutters/Python-Linux-template
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    'toga-android',
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/trey/.virtualenvs/guesser/lib/python3.6/site-packages/briefcase/app.py", line 336, in run
    self.generate_app_template()
  File "/home/trey/.virtualenvs/guesser/lib/python3.6/site-packages/briefcase/app.py", line 195, in generate_app_template
    'secret_key': self.secret_key,
  File "/home/trey/.virtualenvs/guesser/lib/python3.6/site-packages/cookiecutter/main.py", line 63, in cookiecutter
    no_input=no_input,
  File "/home/trey/.virtualenvs/guesser/lib/python3.6/site-packages/cookiecutter/repository.py", line 101, in determine_repo_dir
    '\n'.join(repository_candidates)
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "/home/trey/.cookiecutters/Python-Linux-template" could not be found in the following locations:
/home/trey/.cookiecutters/Python-Linux-template
/home/trey/.cookiecutters/Python-Linux-template
```

Is there another cookiecutter template I need to install from somewhere?

**Comment by treyhunner** [comment]
It turns out that this was a problem caused by #61, which results in a partially-installed (corrupted) `Project-Linux-template` cookiecutter directory.
